# Generated by Django 4.0.5 on 2022-07-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='profile_picture',
            field=models.ImageField(default='default.png', upload_to='picture/%y/%m/%d', verbose_name='profile picture'),
        ),
        migrations.AddField(
            model_name='nomad',
            name='profile_picture',
            field=models.ImageField(default='default.png', upload_to='picture/%y/%m/%d', verbose_name='profile picture'),
        ),
    ]
