# Generated by Django 3.0.4 on 2020-03-11 15:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidence',
            options={'verbose_name_plural': 'Incidences'},
        ),
        migrations.AlterField(
            model_name='incidence',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
